// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package cn.shuye00123.netty.client.protobuf;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.Sample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 errcode = 1;</code>
     */
    int getErrcode();

    /**
     * <code>string errmsg = 2;</code>
     */
    String getErrmsg();
    /**
     * <code>string errmsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrmsgBytes();

    /**
     * <code>string hint = 3;</code>
     */
    String getHint();
    /**
     * <code>string hint = 3;</code>
     */
    com.google.protobuf.ByteString
        getHintBytes();

    /**
     * <code>.netty.Sample.MyObject obj = 4;</code>
     */
    boolean hasObj();
    /**
     * <code>.netty.Sample.MyObject obj = 4;</code>
     */
    Sample.MyObject getObj();
    /**
     * <code>.netty.Sample.MyObject obj = 4;</code>
     */
    Sample.MyObjectOrBuilder getObjOrBuilder();
  }
  /**
   * Protobuf type {@code netty.Sample}
   */
  public  static final class Sample extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netty.Sample)
      SampleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Sample.newBuilder() to construct.
    private Sample(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sample() {
      errcode_ = 0;
      errmsg_ = "";
      hint_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Sample(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              errcode_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              errmsg_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              hint_ = s;
              break;
            }
            case 34: {
              MyObject.Builder subBuilder = null;
              if (obj_ != null) {
                subBuilder = obj_.toBuilder();
              }
              obj_ = input.readMessage(MyObject.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(obj_);
                obj_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TestProto.internal_static_netty_Sample_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TestProto.internal_static_netty_Sample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Sample.class, Builder.class);
    }

    public interface MyObjectOrBuilder extends
        // @@protoc_insertion_point(interface_extends:netty.Sample.MyObject)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 id = 1;</code>
       */
      int getId();

      /**
       * <code>repeated string str = 2;</code>
       */
      java.util.List<String>
          getStrList();
      /**
       * <code>repeated string str = 2;</code>
       */
      int getStrCount();
      /**
       * <code>repeated string str = 2;</code>
       */
      String getStr(int index);
      /**
       * <code>repeated string str = 2;</code>
       */
      com.google.protobuf.ByteString
          getStrBytes(int index);
    }
    /**
     * Protobuf type {@code netty.Sample.MyObject}
     */
    public  static final class MyObject extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:netty.Sample.MyObject)
        MyObjectOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use MyObject.newBuilder() to construct.
      private MyObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private MyObject() {
        id_ = 0;
        str_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private MyObject(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                id_ = input.readInt32();
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  str_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000002;
                }
                str_.add(s);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            str_ = str_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestProto.internal_static_netty_Sample_MyObject_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestProto.internal_static_netty_Sample_MyObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MyObject.class, Builder.class);
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private int id_;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }

      public static final int STR_FIELD_NUMBER = 2;
      private com.google.protobuf.LazyStringList str_;
      /**
       * <code>repeated string str = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStrList() {
        return str_;
      }
      /**
       * <code>repeated string str = 2;</code>
       */
      public int getStrCount() {
        return str_.size();
      }
      /**
       * <code>repeated string str = 2;</code>
       */
      public String getStr(int index) {
        return str_.get(index);
      }
      /**
       * <code>repeated string str = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStrBytes(int index) {
        return str_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (id_ != 0) {
          output.writeInt32(1, id_);
        }
        for (int i = 0; i < str_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, str_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, id_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < str_.size(); i++) {
            dataSize += computeStringSizeNoTag(str_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getStrList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof MyObject)) {
          return super.equals(obj);
        }
        MyObject other = (MyObject) obj;

        boolean result = true;
        result = result && (getId()
            == other.getId());
        result = result && getStrList()
            .equals(other.getStrList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
        if (getStrCount() > 0) {
          hash = (37 * hash) + STR_FIELD_NUMBER;
          hash = (53 * hash) + getStrList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static MyObject parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MyObject parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MyObject parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MyObject parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MyObject parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MyObject parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MyObject parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MyObject parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static MyObject parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static MyObject parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static MyObject parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MyObject parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(MyObject prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code netty.Sample.MyObject}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:netty.Sample.MyObject)
          MyObjectOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return TestProto.internal_static_netty_Sample_MyObject_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return TestProto.internal_static_netty_Sample_MyObject_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  MyObject.class, Builder.class);
        }

        // Construct using cn.shuye00123.netty.server.protobuf.TestProto.Sample.MyObject.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          id_ = 0;

          str_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return TestProto.internal_static_netty_Sample_MyObject_descriptor;
        }

        public MyObject getDefaultInstanceForType() {
          return MyObject.getDefaultInstance();
        }

        public MyObject build() {
          MyObject result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public MyObject buildPartial() {
          MyObject result = new MyObject(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          result.id_ = id_;
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            str_ = str_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.str_ = str_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof MyObject) {
            return mergeFrom((MyObject)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(MyObject other) {
          if (other == MyObject.getDefaultInstance()) return this;
          if (other.getId() != 0) {
            setId(other.getId());
          }
          if (!other.str_.isEmpty()) {
            if (str_.isEmpty()) {
              str_ = other.str_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureStrIsMutable();
              str_.addAll(other.str_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          MyObject parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (MyObject) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int id_ ;
        /**
         * <code>int32 id = 1;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>int32 id = 1;</code>
         */
        public Builder setId(int value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 id = 1;</code>
         */
        public Builder clearId() {
          
          id_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList str_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureStrIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            str_ = new com.google.protobuf.LazyStringArrayList(str_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated string str = 2;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getStrList() {
          return str_.getUnmodifiableView();
        }
        /**
         * <code>repeated string str = 2;</code>
         */
        public int getStrCount() {
          return str_.size();
        }
        /**
         * <code>repeated string str = 2;</code>
         */
        public String getStr(int index) {
          return str_.get(index);
        }
        /**
         * <code>repeated string str = 2;</code>
         */
        public com.google.protobuf.ByteString
            getStrBytes(int index) {
          return str_.getByteString(index);
        }
        /**
         * <code>repeated string str = 2;</code>
         */
        public Builder setStr(
            int index, String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureStrIsMutable();
          str_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string str = 2;</code>
         */
        public Builder addStr(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureStrIsMutable();
          str_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string str = 2;</code>
         */
        public Builder addAllStr(
            Iterable<String> values) {
          ensureStrIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, str_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string str = 2;</code>
         */
        public Builder clearStr() {
          str_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string str = 2;</code>
         */
        public Builder addStrBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureStrIsMutable();
          str_.add(value);
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:netty.Sample.MyObject)
      }

      // @@protoc_insertion_point(class_scope:netty.Sample.MyObject)
      private static final MyObject DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new MyObject();
      }

      public static MyObject getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<MyObject>
          PARSER = new com.google.protobuf.AbstractParser<MyObject>() {
        public MyObject parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new MyObject(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<MyObject> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<MyObject> getParserForType() {
        return PARSER;
      }

      public MyObject getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errcode_;
    /**
     * <code>int32 errcode = 1;</code>
     */
    public int getErrcode() {
      return errcode_;
    }

    public static final int ERRMSG_FIELD_NUMBER = 2;
    private volatile Object errmsg_;
    /**
     * <code>string errmsg = 2;</code>
     */
    public String getErrmsg() {
      Object ref = errmsg_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        errmsg_ = s;
        return s;
      }
    }
    /**
     * <code>string errmsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrmsgBytes() {
      Object ref = errmsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        errmsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HINT_FIELD_NUMBER = 3;
    private volatile Object hint_;
    /**
     * <code>string hint = 3;</code>
     */
    public String getHint() {
      Object ref = hint_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        hint_ = s;
        return s;
      }
    }
    /**
     * <code>string hint = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHintBytes() {
      Object ref = hint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        hint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OBJ_FIELD_NUMBER = 4;
    private MyObject obj_;
    /**
     * <code>.netty.Sample.MyObject obj = 4;</code>
     */
    public boolean hasObj() {
      return obj_ != null;
    }
    /**
     * <code>.netty.Sample.MyObject obj = 4;</code>
     */
    public MyObject getObj() {
      return obj_ == null ? MyObject.getDefaultInstance() : obj_;
    }
    /**
     * <code>.netty.Sample.MyObject obj = 4;</code>
     */
    public MyObjectOrBuilder getObjOrBuilder() {
      return getObj();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errcode_ != 0) {
        output.writeInt32(1, errcode_);
      }
      if (!getErrmsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errmsg_);
      }
      if (!getHintBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hint_);
      }
      if (obj_ != null) {
        output.writeMessage(4, getObj());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errcode_);
      }
      if (!getErrmsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errmsg_);
      }
      if (!getHintBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hint_);
      }
      if (obj_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getObj());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Sample)) {
        return super.equals(obj);
      }
      Sample other = (Sample) obj;

      boolean result = true;
      result = result && (getErrcode()
          == other.getErrcode());
      result = result && getErrmsg()
          .equals(other.getErrmsg());
      result = result && getHint()
          .equals(other.getHint());
      result = result && (hasObj() == other.hasObj());
      if (hasObj()) {
        result = result && getObj()
            .equals(other.getObj());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrcode();
      hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrmsg().hashCode();
      hash = (37 * hash) + HINT_FIELD_NUMBER;
      hash = (53 * hash) + getHint().hashCode();
      if (hasObj()) {
        hash = (37 * hash) + OBJ_FIELD_NUMBER;
        hash = (53 * hash) + getObj().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Sample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Sample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Sample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Sample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Sample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Sample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Sample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Sample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Sample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.Sample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.Sample)
        SampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TestProto.internal_static_netty_Sample_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TestProto.internal_static_netty_Sample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Sample.class, Builder.class);
      }

      // Construct using cn.shuye00123.netty.server.protobuf.TestProto.Sample.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        errcode_ = 0;

        errmsg_ = "";

        hint_ = "";

        if (objBuilder_ == null) {
          obj_ = null;
        } else {
          obj_ = null;
          objBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TestProto.internal_static_netty_Sample_descriptor;
      }

      public Sample getDefaultInstanceForType() {
        return Sample.getDefaultInstance();
      }

      public Sample build() {
        Sample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Sample buildPartial() {
        Sample result = new Sample(this);
        result.errcode_ = errcode_;
        result.errmsg_ = errmsg_;
        result.hint_ = hint_;
        if (objBuilder_ == null) {
          result.obj_ = obj_;
        } else {
          result.obj_ = objBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Sample) {
          return mergeFrom((Sample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Sample other) {
        if (other == Sample.getDefaultInstance()) return this;
        if (other.getErrcode() != 0) {
          setErrcode(other.getErrcode());
        }
        if (!other.getErrmsg().isEmpty()) {
          errmsg_ = other.errmsg_;
          onChanged();
        }
        if (!other.getHint().isEmpty()) {
          hint_ = other.hint_;
          onChanged();
        }
        if (other.hasObj()) {
          mergeObj(other.getObj());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Sample parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Sample) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int errcode_ ;
      /**
       * <code>int32 errcode = 1;</code>
       */
      public int getErrcode() {
        return errcode_;
      }
      /**
       * <code>int32 errcode = 1;</code>
       */
      public Builder setErrcode(int value) {
        
        errcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errcode = 1;</code>
       */
      public Builder clearErrcode() {
        
        errcode_ = 0;
        onChanged();
        return this;
      }

      private Object errmsg_ = "";
      /**
       * <code>string errmsg = 2;</code>
       */
      public String getErrmsg() {
        Object ref = errmsg_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          errmsg_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string errmsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrmsgBytes() {
        Object ref = errmsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          errmsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errmsg = 2;</code>
       */
      public Builder setErrmsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errmsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string errmsg = 2;</code>
       */
      public Builder clearErrmsg() {
        
        errmsg_ = getDefaultInstance().getErrmsg();
        onChanged();
        return this;
      }
      /**
       * <code>string errmsg = 2;</code>
       */
      public Builder setErrmsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errmsg_ = value;
        onChanged();
        return this;
      }

      private Object hint_ = "";
      /**
       * <code>string hint = 3;</code>
       */
      public String getHint() {
        Object ref = hint_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          hint_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string hint = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHintBytes() {
        Object ref = hint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          hint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string hint = 3;</code>
       */
      public Builder setHint(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hint_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string hint = 3;</code>
       */
      public Builder clearHint() {
        
        hint_ = getDefaultInstance().getHint();
        onChanged();
        return this;
      }
      /**
       * <code>string hint = 3;</code>
       */
      public Builder setHintBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        hint_ = value;
        onChanged();
        return this;
      }

      private MyObject obj_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          MyObject, MyObject.Builder, MyObjectOrBuilder> objBuilder_;
      /**
       * <code>.netty.Sample.MyObject obj = 4;</code>
       */
      public boolean hasObj() {
        return objBuilder_ != null || obj_ != null;
      }
      /**
       * <code>.netty.Sample.MyObject obj = 4;</code>
       */
      public MyObject getObj() {
        if (objBuilder_ == null) {
          return obj_ == null ? MyObject.getDefaultInstance() : obj_;
        } else {
          return objBuilder_.getMessage();
        }
      }
      /**
       * <code>.netty.Sample.MyObject obj = 4;</code>
       */
      public Builder setObj(MyObject value) {
        if (objBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          obj_ = value;
          onChanged();
        } else {
          objBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.netty.Sample.MyObject obj = 4;</code>
       */
      public Builder setObj(
          MyObject.Builder builderForValue) {
        if (objBuilder_ == null) {
          obj_ = builderForValue.build();
          onChanged();
        } else {
          objBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.netty.Sample.MyObject obj = 4;</code>
       */
      public Builder mergeObj(MyObject value) {
        if (objBuilder_ == null) {
          if (obj_ != null) {
            obj_ =
              MyObject.newBuilder(obj_).mergeFrom(value).buildPartial();
          } else {
            obj_ = value;
          }
          onChanged();
        } else {
          objBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.netty.Sample.MyObject obj = 4;</code>
       */
      public Builder clearObj() {
        if (objBuilder_ == null) {
          obj_ = null;
          onChanged();
        } else {
          obj_ = null;
          objBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.netty.Sample.MyObject obj = 4;</code>
       */
      public MyObject.Builder getObjBuilder() {
        
        onChanged();
        return getObjFieldBuilder().getBuilder();
      }
      /**
       * <code>.netty.Sample.MyObject obj = 4;</code>
       */
      public MyObjectOrBuilder getObjOrBuilder() {
        if (objBuilder_ != null) {
          return objBuilder_.getMessageOrBuilder();
        } else {
          return obj_ == null ?
              MyObject.getDefaultInstance() : obj_;
        }
      }
      /**
       * <code>.netty.Sample.MyObject obj = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MyObject, MyObject.Builder, MyObjectOrBuilder>
          getObjFieldBuilder() {
        if (objBuilder_ == null) {
          objBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MyObject, MyObject.Builder, MyObjectOrBuilder>(
                  getObj(),
                  getParentForChildren(),
                  isClean());
          obj_ = null;
        }
        return objBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netty.Sample)
    }

    // @@protoc_insertion_point(class_scope:netty.Sample)
    private static final Sample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Sample();
    }

    public static Sample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sample>
        PARSER = new com.google.protobuf.AbstractParser<Sample>() {
      public Sample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Sample(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Sample> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Sample> getParserForType() {
      return PARSER;
    }

    public Sample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Sample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_Sample_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Sample_MyObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_Sample_MyObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ntest.proto\022\005netty\"\201\001\n\006Sample\022\017\n\007errcod" +
      "e\030\001 \001(\005\022\016\n\006errmsg\030\002 \001(\t\022\014\n\004hint\030\003 \001(\t\022#\n" +
      "\003obj\030\004 \001(\0132\026.netty.Sample.MyObject\032#\n\010My" +
      "Object\022\n\n\002id\030\001 \001(\005\022\013\n\003str\030\002 \003(\tB0\n#cn.sh" +
      "uye00123.netty.server.protobufB\tTestProt" +
      "ob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netty_Sample_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_Sample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_Sample_descriptor,
        new String[] { "Errcode", "Errmsg", "Hint", "Obj", });
    internal_static_netty_Sample_MyObject_descriptor =
      internal_static_netty_Sample_descriptor.getNestedTypes().get(0);
    internal_static_netty_Sample_MyObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_Sample_MyObject_descriptor,
        new String[] { "Id", "Str", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
